# Generated by Django 6.0 on 2026-01-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_commenthistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('iq', models.IntegerField(default=0, verbose_name='IQ')),
                ('happi_index', models.IntegerField(default=0, verbose_name='HAPPI_INDEX')),
            ],
            options={
                'verbose_name': 'О студенте',
            },
        ),
    ]
