# Generated by Django 6.0 on 2026-01-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_studenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'ordering': ['-id'], 'verbose_name': 'О студенте', 'verbose_name_plural': 'О студенте'},
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
