# Generated by Django 6.0 on 2026-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='amount_of_products',
            field=models.TextField(verbose_name='Количество продуктов'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='list_of_products',
            field=models.TextField(verbose_name='Список продуктов'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='products',
            field=models.TextField(blank=True, default='', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.TextField(blank=True, default='', verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch',
            field=models.TextField(blank=True, default='', verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alergens',
            field=models.TextField(blank=True, default='', verbose_name='Аллергены'),
        ),
        migrations.AlterField(
            model_name='user',
            name='alergens',
            field=models.TextField(blank=True, default='', verbose_name='Аллергены'),
        ),
    ]
